### PR TITLE
Fix warning message and check length clue.

### PR DESCRIPTION
**Pull request by BruceGoodGuy**
Fix the issue: I got a warning message when attempting a quiz containing crossword qtype.

### CODE REVIEW

**Comment by vuvanhieu143** [comment]
Hi @timhunt ,
we have fixed the warning when we pass to much data into the js_call_amd function.
But we have one small issue.
We can't seem to get bypass the git action for grunt.
Despite we min the js with correct node version and grunt version for Moodle 4.0.
This is the version we use to min the js file.
grunt-cli v1.4.3
grunt v1.4.1
node v16.14.2
Do you have any advice on how to fix the git-action grunt issue?

Many thanks.

**Comment by timhunt** [comment]
Note, we need a clean CI build.

And, if you check the build configuration (https://github.com/moodleou/moodle-qtype_crossword/blob/main/.github/workflows/ci.yml#L107) it is only running grunt on Moodle 4.0.x, since the build output changes for different Moodle versions. Anyway, that is why it is only failing on the 4.0 branch - and it needs to be fixed.

Alos, you have not explained what you are changing and why. Please explain.

Why do we want to limit clues to 200 chars? That just seems wrong to me. I don't see any need to impose a limit. We don't konw what teachers are teaching. We need to trust them to know best.

Some other points:

1. Don't use mb_strlen in Moodle. Use the core_text:: library
2. To access data attributes on an element, don't do el.getAttribute('data-questionid'). Do el.dataset.questionid.
3. ... and, is the explicit parseInt really necessary/desirable?

**Comment by timhunt** [comment]
Thanks for the replies.

Re 1. In Moodle DB, CHAR column are limited ot 1333 chars. So, probably making these colunns CHAR(1333) is good enough. And, I agree that if there is a limit in the DB, it is good to validate and give a nice message in the UI, rather than a database exception, so good idea.

**Comment by BruceGoodGuy** [comment]
Hi @timhunt,
In the [commit ](https://github.com/moodleou/moodle-qtype_crossword/pull/2/commits/9d1f3171c19f222f09e989eb149f668c85f1693b) : 9d1f3171c19f222f09e989eb149f668c85f1693b (branch wip608619), I have done following works below:
- Using el.dataset instead of el.getAtributes.
- Creating upgrade.php to set the max length of the clue column up to 1333 characters also adding validation.
Could you please help me to review it? thanks.

**Comment by timhunt** [comment]
Thanks. Reviewed and merged.

**Pull request merged**
