### PR TITLE
Quiz\Crossword: Change crossword input behavior and show hints.

### PR DESCRIPTION
**Pull request by BruceGoodGuy**
Hi @timhunt ,

Based on your suggestion which is described in AC from ticket 625911. I have implemented it in this commitment.

Because this ticket needs to change the behaviour when rendering the crossword as well as change the events when interacting with it. So I updated quite a few lines of code in many functions to make sure it worked properly. I'm sorry that the code has changed quite a bit and it will take you longer to review.

With a new behaviour when users create crossword questions with answers: AB-C, BB C and A-C-B.
And here is the new UI when previewing this question: 
image

And this is the new UI when attempting it:
image

Please help me review and give me feedback if anything makes you unsatisfied. Thanks very much.

### CODE REVIEW

**Comment by BruceGoodGuy** [comment]
Updated: I just rebased this commit with the latest code on the main branch.

**Comment by BruceGoodGuy** [comment]
Updated:
I created a new commit for this ticket: [Quiz\Crossword: Rebase code and fix minor issue](https://github.com/moodleou/moodle-qtype_crossword/pull/12/commits/96d13b22251c8ea9cae6190d6e3dd08dffb7a53a).
In this commit, I did more things:
- Rebase with the latest code on the main branch and adjust the code to adapt to recent changes.
- Fix minor an issue in mobile:
    It must compile instead of showing the HTML clue text like this:
MicrosoftTeams-image (2)
   So I fixed it to show like this:
MicrosoftTeams-image (3).

Could you please help me to review it?
Thanks @timhunt.

**Comment by timhunt** [comment]
Having merged the other issue, I have now rebased this. On branch https://github.com/moodleou/moodle-qtype_crossword/tree/wip625911-tim. Will review next week.

**Comment by timhunt** [comment]
I have now finished reviewing. I made some tweaks to tidy things up, which cna be seen here: https://github.com/moodleou/moodle-qtype_crossword/commit/ad761e619573709913cad57d54c3624c902a108a. I am about to push this to main, so closing.

**Pull request closed without merging**
